### ISSUE TITLE
Publishing while consuming

### ISSUE THREAD

**Issue by decaz** [mosquito/aio-pika#25]
The worker should get new task from the _task_queue_, publish new message into the _task_queue2_ and acknowledge the received task from the _task_queue_.

Let's assume that the worker is not running. Now run _new_task.py_: 3 tasks were sent into the _task_queue_. Now run _worker.py_: 3 tasks were received from the _task_queue_, 3 tasks were sent into the _task_queue2_, BUT 1 task left **unacknowledged** in the _task_queue_. Can you help me to get to the reason, why? Maybe I am doing something wrong?

P.S.: Number of tasks in the new_task.py (default is 3) can be changed - **the higher this number is, the more unacknowledged tasks are left in the _task_queue_ after running the worker**.

**new_task.py**
```python
import asyncio
from aio_pika import connect, Message, DeliveryMode

async def main():
    connection = await connect("amqp://guest:guest@rabbit/")
    channel = await connection.channel()
    message_body = b"Hello World!"
    message = Message(message_body, delivery_mode=DeliveryMode.PERSISTENT)
    for _ in range(3):
        await channel.default_exchange.publish(message, routing_key='task_queue')
        print("Sent %r" % message)
    await connection.close()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

**worker.py**
```python
import asyncio
from aio_pika import connect, IncomingMessage, Message, DeliveryMode

channel = None

async def on_message(message):
    with message.process():
        print("Received message %r" % message.body)
        new_message = Message(b'New message', delivery_mode=DeliveryMode.PERSISTENT)
        await channel.default_exchange.publish(new_message, routing_key='task_queue2')

async def main():
    global channel
    connection = await connect("amqp://guest:guest@rabbit/")
    channel = await connection.channel()
    queue = await channel.declare_queue('task_queue', durable=True)
    await channel.declare_queue('task_queue2', durable=True)
    queue.consume(on_message)

loop = asyncio.get_event_loop()
loop.create_task(main())
loop.run_forever()
```

**Comment by mosquito** [comment]
Hmm... try to enable `backpressure_detection` like `connect(..., backpressure_detection=True)`

**Comment by mosquito** [comment]
Ok. I already produced it. I guess that's bug.

**Comment by mosquito** [comment]
Can you test my fixes in #26 

I was able to reproduce it only this [examples](https://github.com/mosquito/aio-pika/pull/26#issuecomment-303832867)

**Comment by decaz** [comment]
@mosquito I'm grateful for that!

I guess there is unfortunately some regression after upgrading to 0.10.4:
```python
import asyncio
from aio_pika import connect

async def main():
    connection = await connect("amqp://guest:guest@rabbit/")
    connection.add_close_callback(lambda f: f)

loop = asyncio.get_event_loop()
loop.create_task(main())
loop.run_forever()
```
```
$ python rabbitmq.py 
Task exception was never retrieved
future: <Task finished coro=<main() done, defined at new.py:4> exception=AttributeError("'NoneType' object has no attribute 'add_done_callback'",)>
Traceback (most recent call last):
  File "new.py", line 6, in main
    connection.add_close_callback(lambda f: f)
  File "/tmp/venv/lib/python3.6/site-packages/aio_pika/connection.py", line 80, in add_close_callback
    self.__closing.add_done_callback(callback)
AttributeError: 'NoneType' object has no attribute 'add_done_callback'
```

**Comment by mosquito** [comment]
The test for this already added. Bug was fixed.

**Comment by decaz** [comment]
@mosquito Thanks!
